//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemini.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gemini.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to set value: {0} ähnelt.
        /// </summary>
        public static string AdvancedSliderCommitErrorFormat {
            get {
                return ResourceManager.GetString("AdvancedSliderCommitErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All Files ähnelt.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All Supported Files ähnelt.
        /// </summary>
        public static string AllSupportedFiles {
            get {
                return ResourceManager.GetString("AllSupportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Edit ähnelt.
        /// </summary>
        public static string EditMenuText {
            get {
                return ResourceManager.GetString("EditMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Redo ähnelt.
        /// </summary>
        public static string EditRedoCommandText {
            get {
                return ResourceManager.GetString("EditRedoCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Redo ähnelt.
        /// </summary>
        public static string EditRedoCommandToolTip {
            get {
                return ResourceManager.GetString("EditRedoCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Undo ähnelt.
        /// </summary>
        public static string EditUndoCommandText {
            get {
                return ResourceManager.GetString("EditUndoCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Undo ähnelt.
        /// </summary>
        public static string EditUndoCommandToolTip {
            get {
                return ResourceManager.GetString("EditUndoCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Close ähnelt.
        /// </summary>
        public static string FileCloseCommandText {
            get {
                return ResourceManager.GetString("FileCloseCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string FileCloseCommandToolTip {
            get {
                return ResourceManager.GetString("FileCloseCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E_xit ähnelt.
        /// </summary>
        public static string FileExitCommandText {
            get {
                return ResourceManager.GetString("FileExitCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        public static string FileExitCommandToolTip {
            get {
                return ResourceManager.GetString("FileExitCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _File ähnelt.
        /// </summary>
        public static string FileMenuText {
            get {
                return ResourceManager.GetString("FileMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _New ähnelt.
        /// </summary>
        public static string FileNewCommandText {
            get {
                return ResourceManager.GetString("FileNewCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        public static string FileNewCommandToolTip {
            get {
                return ResourceManager.GetString("FileNewCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Untitled {0} ähnelt.
        /// </summary>
        public static string FileNewUntitled {
            get {
                return ResourceManager.GetString("FileNewUntitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Open ähnelt.
        /// </summary>
        public static string FileOpenCommandText {
            get {
                return ResourceManager.GetString("FileOpenCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        public static string FileOpenCommandToolTip {
            get {
                return ResourceManager.GetString("FileOpenCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recent Files ähnelt.
        /// </summary>
        public static string FileRecentFilesCommandText {
            get {
                return ResourceManager.GetString("FileRecentFilesCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recent Files ähnelt.
        /// </summary>
        public static string FileRecentFilesCommandToolTip {
            get {
                return ResourceManager.GetString("FileRecentFilesCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save All ähnelt.
        /// </summary>
        public static string FileSaveAllCommandText {
            get {
                return ResourceManager.GetString("FileSaveAllCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save All ähnelt.
        /// </summary>
        public static string FileSaveAllCommandToolTip {
            get {
                return ResourceManager.GetString("FileSaveAllCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save _As... ähnelt.
        /// </summary>
        public static string FileSaveAsCommandText {
            get {
                return ResourceManager.GetString("FileSaveAsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save As ähnelt.
        /// </summary>
        public static string FileSaveAsCommandToolTip {
            get {
                return ResourceManager.GetString("FileSaveAsCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Save ähnelt.
        /// </summary>
        public static string FileSaveCommandText {
            get {
                return ResourceManager.GetString("FileSaveCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string FileSaveCommandToolTip {
            get {
                return ResourceManager.GetString("FileSaveCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Help ähnelt.
        /// </summary>
        public static string HelpMenuText {
            get {
                return ResourceManager.GetString("HelpMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die History ähnelt.
        /// </summary>
        public static string HistoryDisplayName {
            get {
                return ResourceManager.GetString("HistoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initial State ähnelt.
        /// </summary>
        public static string HistoryInitialState {
            get {
                return ResourceManager.GetString("HistoryInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System ähnelt.
        /// </summary>
        public static string LanguageSystem {
            get {
                return ResourceManager.GetString("LanguageSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto hide main menu ähnelt.
        /// </summary>
        public static string MainMenuSettingsAutoHideMainMenu {
            get {
                return ResourceManager.GetString("MainMenuSettingsAutoHideMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color Theme: ähnelt.
        /// </summary>
        public static string MainMenuSettingsColorTheme {
            get {
                return ResourceManager.GetString("MainMenuSettingsColorTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language: ähnelt.
        /// </summary>
        public static string MainMenuSettingsLanguage {
            get {
                return ResourceManager.GetString("MainMenuSettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Requires restart ähnelt.
        /// </summary>
        public static string MainMenuSettingsLanguageRestart {
            get {
                return ResourceManager.GetString("MainMenuSettingsLanguageRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die [Default Title] ähnelt.
        /// </summary>
        public static string MainWindowDefaultTitle {
            get {
                return ResourceManager.GetString("MainWindowDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save changes to the {0} &quot;{1}&quot; before closing? ähnelt.
        /// </summary>
        public static string SaveChangesBeforeClosingMessage {
            get {
                return ResourceManager.GetString("SaveChangesBeforeClosingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        public static string SettingsDisplayName {
            get {
                return ResourceManager.GetString("SettingsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string SettingsPageGeneral {
            get {
                return ResourceManager.GetString("SettingsPageGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Environment ähnelt.
        /// </summary>
        public static string SettingsPathEnvironment {
            get {
                return ResourceManager.GetString("SettingsPathEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blue ähnelt.
        /// </summary>
        public static string ThemeBlueName {
            get {
                return ResourceManager.GetString("ThemeBlueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dark ähnelt.
        /// </summary>
        public static string ThemeDarkName {
            get {
                return ResourceManager.GetString("ThemeDarkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light ähnelt.
        /// </summary>
        public static string ThemeLightName {
            get {
                return ResourceManager.GetString("ThemeLightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standard ähnelt.
        /// </summary>
        public static string ToolBarStandard {
            get {
                return ResourceManager.GetString("ToolBarStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Category ähnelt.
        /// </summary>
        public static string ToolboxCategory {
            get {
                return ResourceManager.GetString("ToolboxCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toolbox ähnelt.
        /// </summary>
        public static string ToolboxDisplayName {
            get {
                return ResourceManager.GetString("ToolboxDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Tools ähnelt.
        /// </summary>
        public static string ToolsMenuText {
            get {
                return ResourceManager.GetString("ToolsMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Options ähnelt.
        /// </summary>
        public static string ToolsOptionsCommandText {
            get {
                return ResourceManager.GetString("ToolsOptionsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        public static string ToolsOptionsCommandToolTip {
            get {
                return ResourceManager.GetString("ToolsOptionsCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Full Screen ähnelt.
        /// </summary>
        public static string ViewFullScreenCommandText {
            get {
                return ResourceManager.GetString("ViewFullScreenCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Full Screen ähnelt.
        /// </summary>
        public static string ViewFullScreenCommandToolTip {
            get {
                return ResourceManager.GetString("ViewFullScreenCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _History ähnelt.
        /// </summary>
        public static string ViewHistoryCommandText {
            get {
                return ResourceManager.GetString("ViewHistoryCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die History ähnelt.
        /// </summary>
        public static string ViewHistoryCommandToolTip {
            get {
                return ResourceManager.GetString("ViewHistoryCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _View ähnelt.
        /// </summary>
        public static string ViewMenuText {
            get {
                return ResourceManager.GetString("ViewMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toolbo_x ähnelt.
        /// </summary>
        public static string ViewToolboxCommandText {
            get {
                return ResourceManager.GetString("ViewToolboxCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toolbox ähnelt.
        /// </summary>
        public static string ViewToolboxCommandToolTip {
            get {
                return ResourceManager.GetString("ViewToolboxCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Window ähnelt.
        /// </summary>
        public static string WindowMenuText {
            get {
                return ResourceManager.GetString("WindowMenuText", resourceCulture);
            }
        }
    }
}
